export interface IPost {
    id: number;
    created_at: string;
    uploader_id: number;
    score: number;
    source: string;
    md5: string;
    last_comment_bumped_at: string;
    rating: string;
    image_width: number;
    image_height: number;
    tag_string: string;
    is_note_locked: boolean;
    fav_count: number;
    file_ext: string;
    last_noted_at: string;
    is_rating_locked: boolean;
    parent_id: number;
    has_children: boolean;
    approver_id: number;
    tag_count_general: number;
    tag_count_artist: number;
    tag_count_character: number;
    tag_count_copyright: number;
    file_size: number;
    is_status_locked: boolean;
    up_score: number;
    down_score: number;
    is_pending: boolean;
    is_flagged: boolean;
    is_deleted: boolean;
    tag_count: boolean;
    updated_at: string;
    is_banned: boolean;
    pixiv_id: number;
    last_commented_at: string;
    has_active_children: boolean;
    bit_flags: number;
    tag_count_meta: number;
    has_large: any;
    has_visible_children: boolean;
    tag_string_general: string;
    tag_string_character: string;
    tag_string_copyright: string;
    tag_string_artist: string;
    tag_string_meta: string;
    file_url: string;
    large_file_url: string;
    preview_file_url: string;
}

export class Post {
    id: number;
    created_at: Date;
    uploader_id: number;
    score: number;
    source: string;
    md5: string;
    last_comment_bumped_at: string;
    rating: string;
    image_width: number;
    image_height: number;
    tags: string[];
    is_note_locked: boolean;
    fav_count: number;
    file_ext: string;
    last_noted_at: string;
    is_rating_locked: boolean;
    parent_id: number;
    has_children: boolean;
    approver_id: number;
    tag_count_general: number;
    tag_count_artist: number;
    tag_count_character: number;
    tag_count_copyright: number;
    file_size: number;
    is_status_locked: boolean;
    up_score: number;
    down_score: number;
    is_pending: boolean;
    is_flagged: boolean;
    is_deleted: boolean;
    tag_count: boolean;
    updated_at: string;
    is_banned: boolean;
    pixiv_id: number;
    last_commented_at: string;
    has_active_children: boolean;
    bit_flags: number;
    tag_count_meta: number;
    has_large: any;
    has_visible_children: boolean;
    tag_general: string[];
    tag_character: string[];
    tag_copyright: string[];
    tag_artist: string[];
    tag_meta: string[];
    file_url: string;
    large_file_url: string;
    preview_file_url: string;

    constructor(private readonly _post: IPost) {
        this.id = this._post.id;
        this.created_at = new Date(this._post.created_at);
        this.uploader_id = this._post.uploader_id;
        this.score = this._post.score;
        this.source = this._post.source;
        this.md5 = this._post.md5;
        this.last_comment_bumped_at = this._post.last_comment_bumped_at;
        this.rating = this._post.rating;
        this.image_width = this._post.image_width;
        this.image_height = this._post.image_height;
        this.tags = this._post.tag_string.split(" ");
        this.is_note_locked = this._post.is_note_locked;
        this.fav_count = this._post.fav_count;
        this.file_ext = this._post.file_ext;
        this.last_noted_at = this._post.last_noted_at;
        this.is_rating_locked = this._post.is_rating_locked;
        this.parent_id = this._post.parent_id;
        this.has_children = this._post.has_children;
        this.approver_id = this._post.approver_id;
        this.tag_count_general = this._post.tag_count_general;
        this.tag_count_artist = this._post.tag_count_artist;
        this.tag_count_character = this._post.tag_count_character;
        this.tag_count_copyright = this._post.tag_count_copyright;
        this.file_size = this._post.file_size;
        this.is_status_locked = this._post.is_status_locked;
        this.up_score = this._post.up_score;
        this.down_score = this._post.down_score;
        this.is_pending = this._post.is_pending;
        this.is_flagged = this._post.is_flagged;
        this.is_deleted = this._post.is_deleted;
        this.tag_count = this._post.tag_count;
        this.updated_at = this._post.updated_at;
        this.is_banned = this._post.is_banned;
        this.pixiv_id = this._post.pixiv_id;
        this.last_commented_at = this._post.last_commented_at;
        this.has_active_children = this._post.has_active_children;
        this.bit_flags = this._post.bit_flags;
        this.tag_count_meta = this._post.tag_count_meta;
        this.has_large = this._post.has_large;
        this.has_visible_children = this._post.has_visible_children;
        this.tag_general = this._post.tag_string_general.split(" ");
        this.tag_character = this._post.tag_string_character.split(" ");
        this.tag_copyright = this._post.tag_string_copyright.split(" ");
        this.tag_artist = this._post.tag_string_artist.split(" ");
        this.tag_meta = this._post.tag_string_meta.split(" ");
        this.file_url = this._post.file_url;
        this.large_file_url = this._post.large_file_url;
        this.preview_file_url = this._post.preview_file_url;
    }
}
